version: "3.8"

services:
    db:
        container_name: postgres
        image: postgres:13.3-alpine
        restart: always
        environment: 
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: docker
            POSTGRES_DB: gittin
        ports:
            - "5432:5432"
        volumes:
            - db-only:/var/lib/postgresql/data
    pgadmin:
        container_name: pgadmin
        image: dpage/pgadmin4:5.5
        restart: always
        environment: 
            PGADMIN_DEFAULT_EMAIL: db@db.com
            PGADMIN_DEFAULT_PASSWORD: docker
            PGADMIN_PORT: 80
        ports: 
            - 8080:80
        volumes:
            - db-only-pgadmin:/var/lib/pgadmin
        depends_on: 
            - db
volumes: 
    db-only:
    db-only-pgadmin: