FROM node:14-alpine as base
WORKDIR /usr/app
COPY package.json yarn.lock jest.config.ts tsconfig.json ormconfig.js ./
COPY src ./src

# used for waiting while database container is running to continue with node stuffs
ADD https://github.com/ufoscout/docker-compose-wait/releases/download/2.9.0/wait /wait
RUN chmod +x /wait
RUN yarn install
RUN yarn build

FROM base as dev
WORKDIR /usr/app
ENV NODE_ENV=development
COPY --from=base /usr/app/dist/database/migrations ./
CMD /wait && yarn migration:run && yarn dev

EXPOSE 3000